### ISSUE TITLE
Custom alg list is picking only nightmare set

### ISSUE THREAD

**Issue by gpjalocha** [nbwzx/blddb#5]
I noticed that when creating custom algs list I can pick only ones from nightmare set(edgeAlgToInfo.json, cornerAlgToInfo.json). I think it should use (edge|corner)AlgToInfoManmade.json. Or at least something in between, like joined set of two of them.
![image](https://github.com/nbwzx/blddb/assets/20863691/1df2faa2-93ea-431c-abae-074ef8d159b6)

**Comment by nbwzx** [comment]
As mentioned in [https://docs.blddb.net/en/](https://docs.blddb.net/en/):
A template spreadsheet will be generated after the user selects a corner buffer. 18 algorithms are provided for each of the cases and the user can choose his/her favorite by clicking the drop-down list. Alternatively, the user can enter algorithms manually (an add menu will appear only if the algorithm entered is correct). Once the algorithm is added, commutator form and recommended grip will be produced automatically.

So you can enter algorithms manually if it is not in the nightmare list.  

I think that adding a drop-down menu later for users to choose the alg styles between nightmare, manmade, etc would be convenient and well sorted. Is that good?

**Comment by gpjalocha** [comment]
> I think that adding a drop-down menu later for users to choose the alg styles between nightmare, manmade, etc would be convenient and well sorted. Is that good?

Yes that's also a good solution.

**Comment by nbwzx** [comment]
Fixed [here](https://github.com/nbwzx/blddb/commit/d0ead90b09d67f5b33d73b3a6c76beb0e1f7eb2e).

An example:
![127 0 0 1_5500_custom_edge html](https://github.com/nbwzx/blddb/assets/55343466/767aded9-fdec-4cd4-aaf1-184e01daba65)


If it works well, I may close this issue.

**Comment by gpjalocha** [comment]
Perfect, thank you
