### ISSUE TITLE
Japanese titles of coner.html and edge.html

### ISSUE THREAD

**Issue by kits** [nbwzx/blddb#6]
In the Japanese version of coner.html, the title is "3-Styleエッジ". However, the correct title is "3-Styleコーナー".

Similarly, in the Japanese version of edge.html, the title is "3-Styleコーナー," but the correct title is "3-Styleエッジ".

Perhaps the following part of assets/js/language.js is incorrect:

>     "ja": {
>         "title": "3BLD手順データベース",
>         "description": "BLDDBのオンラインウェブサイト。",
>       * "corner": "3-Styleエッジ",
>         "twists": "コーナーツイスト",
>       * "edge": "3-Styleコーナー",

 Correct:

>         "corner": "3-Styleコーナー",
>         "edge": "3-Styleエッジ",

**Comment by nbwzx** [comment]
Thanks. I have fixed it.

**Comment by kits** [comment]
Thank you!
